version: '3'
services:
  express:
    build: .
    ports:
      - "3000-3020:3000"
    environment: 
      MONGODB_URI: "mongodb://mongodb:27017/test"
    links:
      - mongodb
    volumes:
      - '.:/usr/app'
  mongodb:
    image: mongo